### ISSUE TITLE
When pressing “run” still takes a few seconds before user feedback is displayed

### ISSUE THREAD

**Issue by jeffreycwitt** [stenskjaer/lbp_print-web-app#9]
When pressing “run” still takes a few seconds before user feedback is displayed. 

We could think using javascript to add an immediate "pinwheel" onSubmit, so that the user knows something has happened. The pinwheel would then be replaced when the user feedback is ready to display.

**Comment by stenskjaer** [comment]
It is difficult for me to reproduce this problem, as I don't really have control over the deployment. But I set up a AWS ECS container service (see http://52.19.25.174/), and when I test that, I get instant feedback when I press run. Is that the same for you?

**Comment by stenskjaer** [comment]
This is temporarily solved by adding a spinning wheel. I think that's all I can do from my end when I don't have control of the deployment.
